spring:
  application:
    name: ossref-batch
  profiles:
    default: local
  batch:
    job:
      enabled: false
  jpa:
    open-in-view: false

server:
  port: 8081

github:
  token: ${GITHUB_TOKEN:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
